version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - /home/hel-makh/data/wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - web-net
    env_file:
      - .env
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - web-net
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/hel-makh/data/wordpress:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - web-net
    depends_on:
      - mariadb
      - nginx
    env_file:
      - .env
    restart: always

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /home/hel-makh/data/mariadb

networks:
  web-net:
    name: web-net
    driver: bridge