version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception-net
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/wordpress
    ports:
      - 9000:9000
    networks:
      - inception-net
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    volumes:
      - adminer-data:/var/www/adminer
    ports:
      - 9001:9001
    networks:
      - inception-net
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/wordpress
      - adminer-data:/var/www/adminer
    ports:
      - 443:443
      - 444:444
    networks:
      - inception-net
    depends_on:
      - wordpress
      - adminer
    env_file:
      - .env
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - inception-net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    volumes:
      - wordpress-data:/var/www/wordpress
    ports:
      - 21:21
    networks:
      - inception-net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    networks:
      - inception-net
    env_file:
      - .env
    restart: always
  website:
    build: ./requirements/bonus/website
    container_name: website
    ports:
      - 8081:80
    networks:
      - inception-net
    env_file:
      - .env
    restart: always

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      device: /home/hel-makh/data/mariadb
      o: bind
      type: local
  wordpress-data:
    driver: local
    driver_opts:
      device: /home/hel-makh/data/wordpress
      o: bind
      type: local
  adminer-data:
    driver: local
    driver_opts:
      device: /home/hel-makh/data/adminer
      o: bind
      type: local

networks:
  inception-net:
    name: inception-net
    driver: bridge