version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception-net
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - inception-net
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception-net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - inception-net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      device: /home/hel-makh/data/mariadb
      o: bind
      type: local
  wordpress-data:
    driver: local
    driver_opts:
      device: /home/hel-makh/data/wordpress
      o: bind
      type: local

networks:
  inception-net:
    name: inception-net
    driver: bridge