version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "80:80"
    # stdin_open: true
    # tty: true
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - ../.env